#spring
spring:
  devtools:
    restart:
      enabled: false

  # H2 DATABASE CONFIG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/ddl.sql
    url: jdbc:mysql://localhost:3306/rabbit?&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    platform: h2
    initialization-mode: always
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /rabbit
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口 默认6379
    password: 6bWRO0z7rRAT # Redis服务器连接密码（默认为空）
    #    #在1.x.x的版本时默认使用的jedis客户端，现在是2.x.x版本默认使用的lettuce客户端
    #    # Jedis和Lettuce都是Redis Client
    #    # Jedis 是直连模式，在多个线程间共享一个 Jedis 实例时是线程不安全的，
    #    # 如果想要在多线程环境下使用 Jedis，需要使用连接池，
    #    # 每个线程都去拿自己的 Jedis 实例，当连接数量增多时，物理连接成本就较高了。
    jedis:
      shutdown-timeout: 300ms #关闭超时
      pool:
        max-active: 600 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 300 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    # Lettuce的连接是基于Netty的，连接实例可以在多个线程间共享，
    # 所以，一个多线程的应用可以使用同一个连接实例，而不用担心并发线程的数量。
    # 当然这个也是可伸缩的设计，一个连接实例不够的情况也可以按需增加连接实例。
    # 通过异步的方式可以让我们更好的利用系统资源，而不用浪费线程等待网络或磁盘I/O。
    # Lettuce 是基于 netty 的，netty 是一个多线程、事件驱动的 I/O 框架，
    # 所以 Lettuce 可以帮助我们充分利用异步的优势
    lettuce:
      shutdown-timeout: 300ms #关闭超时
      pool:
        max-active: 600 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 300 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 60000 #连接超时时间（毫秒）

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mappings/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.rabbit.entity
  typeEnumsPackage: org.rabbit.common.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
##logging
#logging:
#  level: warn